#! /usr/bin/awk -f
# Filtered view of lines where only the 5th is showed 
# based on field seperator being ']' - args to this script being -F ] -v withref=no|yes
# litteral \n is replaced with newline.
# referer part is removed when withref=no
{ 
    # time=substr($1,13,8);
    mes=gensub(/(\[[^\]]+\]\s){4}/,"",1,$0);
    mes=gensub(/\\n/,"\n","g",mes);
    if (withref == "no") {
        print gensub(/referer.+$/,"","g",mes);
    } else {
        print mes;
    }
}       

