#! /usr/bin/awk -f
# Filtered view of lines where only the 5th is showed 
# litteral \n is replaced with newline.
# referer part is removed when withref=no
{ 
    # time=substr($1,13,8);
    mes=gensub(/(\[[^\]]+\]\s){4}/,"",1,$0);
    mes=gensub(/\\n/,"\n","g",mes);
    mes=gensub(/\\\\'/,"'","g",mes);
    if (withref == "no") {
        print gensub(/referer.+$/,"","g",mes);
    } else {
        print mes;
    }
}       

