#!/bin/bash
# This script is invoked by application that calls environment variable EDITOR
# a typcall application would be a file manager or an system mime type association
# editor is ownership depent
#
#wmctrl -s2
#jedit $1
pwdabs=`pwd`
pwdbase=`basename $pwdabs`
workspace="$pwdbase.code-workspace"
if [ -f "$workspace" ]; then
	code $workspace $1 &
else
	code $1 &
fi

#	code $1  >/dev/null 2>&1
