#!/bin/bash
# to be used by daily crontab

rsync -a --delete /home/collector /mnt/mcc
rsync -a --delete /home/bvirk/documents /mnt/mcc
cd ~
tar -czf /mnt/mcc/home/tbmail.tgz .thunderbird/
tar -czf /mnt/mcc/home/ssh.tgz .ssh/

function back2hede() {
        rsync -a --delete $1 $2
}
if [ `ip addr|grep 192.168.0.4|wc -l` = 1 ]; then
    back2hede /mnt/mcc/da         bvirk@hede:/home
    back2hede /mnt/mcc/pa         bvirk@hede:/home
    back2hede /mnt/mcc/multimedia bvirk@hede:/home
    back2hede /mnt/mcc/collector  bvirk@hede:/home
#else
#    echo interface not up
fi
