#!/bin/bash
# assign ip address to ethernet interface that is disbled in network manger.
# disabling in network manger was required because something forced it to
# be default gateway in flavour of usb connected mobile broadband.
hedeup=`ip addr|grep 192.168.0.4|wc -l`
if [ $hedeup = 1 ]; then
	echo hede is allready up
else
	sudo ip addr add 192.168.0.4/24 dev enp2s0
	sudo ip link set enp2s0 up
fi
