#!/bin/bash
# synchronise wan ftp dir using lftp

sourceparentdir=/var/www/ipa/
sourcedir=domain/
destdir=www/ipa.bvirk.dk/
if [ ! -d "$sourceparentdir" ]; then
	echo $sourceparentdir do not exists - perhaps not mounted
	exit 1
fi
cd $sourceparentdir
# in following line pass is a placeholder name for the real password
lftp -d -c 'set ftp:ssl-allow true ; set ssl:verify-certificate no; open -u bvirk,"pass" -e "mirror -R -e -x commands/ -x sq.php --delete -n --no-symlinks '"$sourcedir $destdir"'" web12.gigahost.dk'
