#!/bin/bash
# utility to play audio files using audacious
# executing a symbolic link to this file name like a tgz file in karokedir, plays the inside sound.mp3 and shows the lyrics 

karokedir=/mnt/mcc/multimedia/audio/karoke/karokebins
tgzfile=`basename $0`
cd /tmp
rm -f image.png lyrics.txt
tar -xzf $karokedir/$tgzfile.tgz
audacious sound.mp3 &
sleep 1
if [ -e image.png ]; then
    xviewer image.png
fi
if [ -e lyrics.txt ]; then
    less lyrics.txt
fi


