#!/bin/bash
uname2="$(stat --format '%U' "$1")"
if [ $uname2 = "root" ]; then
	sudo vim $1
else
	wmctrl -s0	
#	jedit $1
	dirnam=`dirname $0`
	workspace=`basename $dirnam`.code-workspace
	if [ -f "$workspace" ]; then
		code "$workspace" $1 &
	else
		code $1 &
	fi
#	code $1  >/dev/null 2>&1
fi
