#!/bin/bash

# download sound of youtube video as .m4a and play it using audacious
# syntax: 
#   ytdlaudio youtube_link [format_code]

downloaddir=/mnt/mcc/multimedia/audio/youtubeMusic
url="${1##&}"

if [ -d "$downloaddir" ]; then
    cd $downloaddir
else 
	echo "$downloaddir didn't exists - using current"
fi

if [ "$#" -gt 1 ]; then
	chosenFormat="-f $2"
else
	youtubeDlTmpFile=/tmp/youtube-dl-F-responce
	echo getting  audio mode for $url
	youtube-dl -F $url >$youtubeDlTmpFile
	chosenFormat="-f `grep m4a < $youtubeDlTmpFile |grep "audio only"|head -n 1|sed 's/ .*//'`"
fi

echo chosen format: $chosenFormat 

if [ "${#chosenFormat}" -lt 4 ]; then
	# if something got wrong and no lines with chosenformat exists then print youtube-dl-F-responce
    cat  $youtubeDlTmpFile
else
	youtube-dl --restrict-filenames --exec audacious $chosenFormat $url
fi
